using Microsoft.Xna.Framework;
using System.Collections.Generic;

namespace SpaceDefence.Collision
{
	/// <summary>
	/// This class has been generated by GitHub CoPilot using Claude Sonnet 3.6. 
	/// Took inspiration from https://gist.github.com/MechanicalFerret/a871b49a607292d32d7a
	/// </summary>
	public class QuadTree
	{
		private const int MaxObjects = 10;
		private const int MaxLevels = 5;

		private int _level;
		private Rectangle _bounds;
		private readonly List<GameObject> _objects = new();
		private readonly QuadTree[] _nodes = new QuadTree[4];

		// Simple stack-based pool to avoid per-frame allocations of nodes
		private static readonly Stack<QuadTree> s_pool = new();
		private const int MaxPoolSize = 1024;

		public QuadTree(int level, Rectangle bounds)
		{
			_level = level;
			_bounds = bounds;
		}

		private QuadTree Reinitialize(int level, Rectangle bounds)
		{
			_level = level;
			_bounds = bounds;
			_objects.Clear();
			for (int i = 0; i < 4; i++) _nodes[i] = null;
			return this;
		}

		private static QuadTree Acquire(int level, Rectangle bounds)
		{
			lock (s_pool)
			{
				if (s_pool.Count > 0)
					return s_pool.Pop().Reinitialize(level, bounds);
			}
			return new QuadTree(level, bounds);
		}

		private void ReleaseToPool()
		{
			// release children first
			for (int i = 0; i < 4; i++)
			{
				if (_nodes[i] != null)
				{
					_nodes[i].ReleaseToPool();
					_nodes[i] = null;
				}
			}

			_objects.Clear();

			lock (s_pool)
			{
				if (s_pool.Count < MaxPoolSize)
					s_pool.Push(this);
			}
		}

		public void Clear()
		{
			_objects.Clear();
			for (int i = 0; i < 4; i++)
			{
				if (_nodes[i] != null)
				{
					_nodes[i].ReleaseToPool();
					_nodes[i] = null;
				}
			}
		}

		private void Split()
		{
			int halfW = _bounds.Width / 2;
			int halfH = _bounds.Height / 2;
			int x = _bounds.X, y = _bounds.Y;
			_nodes[0] = Acquire(_level + 1, new Rectangle(x + halfW, y, halfW, halfH));
			_nodes[1] = Acquire(_level + 1, new Rectangle(x, y, halfW, halfH));
			_nodes[2] = Acquire(_level + 1, new Rectangle(x, y + halfH, halfW, halfH));
			_nodes[3] = Acquire(_level + 1, new Rectangle(x + halfW, y + halfH, halfW, halfH));
		}

		private int GetIndex(Rectangle rect)
		{
			int midX = _bounds.X + _bounds.Width / 2;
			int midY = _bounds.Y + _bounds.Height / 2;

			bool top = rect.Y + rect.Height < midY;
			bool bottom = rect.Y > midY;
			bool left = rect.X + rect.Width < midX;
			bool right = rect.X > midX;

			if (left)
			{
				if (top) return 1;
				if (bottom) return 2;
			}
			else if (right)
			{
				if (top) return 0;
				if (bottom) return 3;
			}
			return -1; // Spans multiple quadrants, stays in parent
		}

		public void Insert(GameObject obj)
		{
			if (_nodes[0] != null)
			{
				int index = GetIndex(obj.collider.GetBoundingBox());
				if (index != -1)
				{
					_nodes[index].Insert(obj);
					return;
				}
			}

			_objects.Add(obj);

			if (_objects.Count > MaxObjects && _level < MaxLevels)
			{
				if (_nodes[0] == null) Split();

				int i = 0;
				while (i < _objects.Count)
				{
					int index = GetIndex(_objects[i].collider.GetBoundingBox());
					if (index != -1)
					{
						_nodes[index].Insert(_objects[i]);
						_objects.RemoveAt(i); // No throwaway list allocation
					}
					else i++;
				}
			}
		}

		/// <summary>
		/// Fills the provided list with nearby candidates - avoids allocating a new list each call.
		/// </summary>
		public void Retrieve(List<GameObject> result, Rectangle rect)
		{
			int index = GetIndex(rect);

			if (_nodes[0] != null)
			{
				if (index != -1)
					_nodes[index].Retrieve(result, rect);
				else
					foreach (var node in _nodes)
						node.Retrieve(result, rect);
			}

			result.AddRange(_objects);
		}
	}
}
